
CABIN Benthic data wrangling -- 

This is data downloaded from all regions within the Canadian Aquatic Biomonitoring Network.


```{r}

library(png)
library(dplyr)
library(tidyverse)
library(reticulate)
library(zoo)
library(lubridate)
library(ggplot2)
library(sf)
library(mapview)
library(gridExtra)
library(data.table)
library(scales)

```

1)Load in Benthic CABIN data in one dataframe, with a column of the Region

```{r}

library(data.table)
files <- list.files(path = "/Users/LevyJ/Desktop/CABIN", pattern = "^cabin_benthic.*?\\.csv", full.names = TRUE) 
df_benthic <- map_df(files, ~read_csv(., col_types = cols(.default = "c")), .id = "Region", encoding = 'Latin-1') 

```

2)Rename the columns to be easier to work with
```{r}
df_benthic <- df_benthic %>%
  rename("Site_Visit_ID" = 'SiteVisitID/IdentifiantdeVisite',
         "Site" = "Site/Site",
         "Year" = "Year/Année",
         "Sampling_Device" = "SamplingDevice/Dispositifd'échantillonnage",
         "Kick_Time" = "KickTime/Périodedelapassedufilettroubleau",
         "Mesh_size" = "MeshSize/Maillage",
         "Subsample" =	"SubSample/Sous-échantillon",
         "Julian_day" ="JulianDay/JourJulien",
         "Sample_Number" = "SampleNumber/Numérod'échantillon",
         "Total_sample" ="TotalSample/Échantillontotal",
         "Status" = "Status/État",
         "Taxonomist" = "Taxonomist/Taxonomiste",
         "organization" = "Organization/Organisation",
         "address" = "Address/Adresser",
         "city" = "City/Ville",
         "province" = "Province/Province",
         "phylum" = "Phylum/Phylum",
         "class" = "Class/Classe",
         "Order" = "Order/Ordre",
         "Family" = "Family/Famille",
         "Genus" = "Genus/Genre",
         "Species" = "Species/Espèce",
         "Replicate" = "Replicate/Réplicat",
         "Count" = "Count/Décompte",
         "ITIS" ="ITIS_TSN",
         "Valid" = "Valid/Valide")
```

Add the region names using the region names file
```{r}
Region_names <- read.csv("Region_names.csv", colClasses =c("character", "character", "character")) 

df_benthic <- full_join(df_benthic, Region_names, by = 'Region')


```

3) Select only the test data 
```{r}

#change Status and Subsample Nas to "Unknown" because filter automatically removes NAs.
benthic_no_test <- df_benthic %>%
  replace_na(list(Status = "Unknown", Subsample = "Unknown")) %>% #have correct # of regions til now
  filter(Status != "Test") %>%
  #remove site, just reduce to however many subsamples there are
  select(Region_Name, Subsample, Status) %>% 
  distinct() %>%
  mutate_at(c('Subsample'), as.numeric) %>%
  
  
  
```


```{r}
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7", "#999999", "#E69F00", "#56B4E9")

ggplot(benthic_no_test, aes(x = Region_Name, y = Subsample, fill = Region_Name )) +
geom_boxplot() +
  theme_bw() +
    theme(plot.title =  element_text(size = 10, hjust = .5, face = "bold")) +
       #  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
   stat_boxplot(geom = "errorbar", width = 0.25) +
  ggtitle( "Percent Sorted by Region \n(Potential Reference or Reference Sites) ") +
  theme(legend.position = 'none') +
    #theme(legend.background = element_rect(colour = 'black', fill = 'white', linetype='solid')) +
scale_x_discrete(labels = wrap_format(10)) +
  ylab("Percent Sorted") +
    scale_fill_manual(values=cbPalette)
    #scale_fill_brewer(palette= )

#outlier of 300... ponar sampling device ??
#doesn't look like much difference between %sorted. 




```


```{r}

unique(df_benthic$Sampling_Device)

```



```{r}





```


```{r}




```

